# Site settings
title: Android Smart WebView
email: getmgks@gmail.com
url: https://mgks.github.io/Android-SmartWebView/
description: "This project is developed to help you create Hybrid Android applications with just webview. Hybrid app comes in between webview and native forms, with this project you can embed any existing webpage or setup an Offline HTML/CSS/Javascript based project."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: voinsource

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/infeeds
  - title: facebook
    url: https://www.facebook.com/infeeds
  - title: stack-overflow
    url: https://stackoverflow.com/questions/tagged/swv
  - title: github
    url: https://github.com/mgks

# Build settings
markdown: kramdown
permalink: pretty
